name: DiscordClub
main: com.elmakers.mine.bukkit.plugins.club.DiscordClubPlugin
version: 1.0
api-version: 1.17
author: NathanWolf
description: A discord bot as a bukkit plugin for some reason

commands:
  eliza:
    description: Get some therapy
    permission: eliza

permissions:
  eliza:
    description: Can use the /eliza command
    type: boolean
    default: op
